INSERT INTO USUARIO(nome, email, senha) VALUES('Aluno', 'aluno@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');

INSERT INTO ORDEM_SERVICO(codOS,
                    data_Finalizacao,
                    dataOS,
                    descricao_Problema,
                    descricao_Servico,
                    quilometragem,
                    statusOS,
                    total_Produtos,
                    total_Servico,
                    valor_Servico,
                    valor_Total,
                    placa_Veiculo,
                    chassi_Veiculo,
                    cor_Veiculo,
                    marca_Veiculo,
                    modelo_Veiculo,
                    nome_Cliente)
            VALUES('2',
                    '2016-06-08',
                    '2016-06-08',
                    'troca oleo e filtro',
                    '',
                    '29.304',
                    '2',
                    '0',
                    '170.00',
                    '0',
                    '170.00',
                    'IXY-6060',
                    '',
                    'Prata',
                    'Honda',
                    'Falcon',
                    'Marlon Magannha Lemos');
INSERT INTO ORDEM_SERVICO(codOS,
                    data_Finalizacao,
                    dataOS,
                    descricao_Problema,
                    descricao_Servico,
                    quilometragem,
                    statusOS,
                    total_Produtos,
                    total_Servico,
                    valor_Servico,
                    valor_Total,
                    placa_Veiculo,
                    chassi_Veiculo,
                    cor_Veiculo,
                    marca_Veiculo,
                    modelo_Veiculo,
                    nome_Cliente)
            VALUES('3',
                    '2016-06-08',
                    '2016-06-08',
                    'troca de pastilha de freio',
                    '',
                    '',
                    '2',
                    '0',
                    '30.00',
                    '0',
                    '30.00',
                    'ISB-6519',
                    '',
                    'Preto/Vermelho',
                    'Kasinski',
                    'Mirage 250',
                    'Paulo Celso Ishida');
INSERT INTO ORDEM_SERVICO(codOS,
                    data_Finalizacao,
                    dataOS,
                    descricao_Problema,
                    descricao_Servico,
                    quilometragem,
                    statusOS,
                    total_Produtos,
                    total_Servico,
                    valor_Servico,
                    valor_Total,
                    placa_Veiculo,
                    chassi_Veiculo,
                    cor_Veiculo,
                    marca_Veiculo,
                    modelo_Veiculo,
                    nome_Cliente)
            VALUES('4',
                    '2016-06-14',
                    '2016-06-10',
                    'troca de óleo \n troca do retentor suspenção \n troca do óleo da suspenção \n busca da peça poa \n m.o',
                    '',
                    '3660',
                    '2',
                    '0',
                    '217.00',
                    '0',
                    '217.00',
                    'SEM-1234',
                    '',
                    'Preto',
                    'Shineray',
                    'Bull',
                    'Ademir Silva');
INSERT INTO ORDEM_SERVICO(codOS,
                    data_Finalizacao,
                    dataOS,
                    descricao_Problema,
                    descricao_Servico,
                    quilometragem,
                    statusOS,
                    total_Produtos,
                    total_Servico,
                    valor_Servico,
                    valor_Total,
                    placa_Veiculo,
                    chassi_Veiculo,
                    cor_Veiculo,
                    marca_Veiculo,
                    modelo_Veiculo,
                    nome_Cliente)
            VALUES('5',
                    '2018-10-10',
                    '2018-06-10',
                    'troca oleo e filtro',
                    '',
                    '50.304',
                    '2',
                    '0',
                    '170.00',
                    '0',
                    '170.00',
                    'IXY-6060',
                    '',
                    'Prata',
                    'Honda',
                    'Falcon',
                    'Marlon Magannha Lemos');