INSERT INTO USUARIO(nome, email, senha) VALUES('Aluno', 'aluno@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');

INSERT INTO ORDEM_SERVICO(codOS,
                    data_Finalizacao,
                    dataOS,
                    descricao_Problema,
                    descricao_Servico,
                    quilometragem,
                    statusOS,
                    total_Produtos,
                    total_Servico,
                    valor_Servico,
                    valor_Total,
                    placa_Veiculo,
                    chassi_Veiculo,
                    cor_Veiculo,
                    marca_Veiculo,
                    modelo_Veiculo,
                    nome_Cliente)
            VALUES('2',
                    '2016-06-08',
                    '2016-06-08',
                    'troca oleo e filtro',
                    '',
                    '29.304',
                    '2',
                    '0',
                    '170.00',
                    '0',
                    '170.00',
                    'IXY-6060',
                    '',
                    'Prata',
                    'Honda',
                    'Falcon',
                    'Marlon Magannha Lemos');
